import {
  AnyPgColumn,
  boolean,
  date,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { organization, team } from "./auth-schema";
import { cases } from "./cases";
import { clients } from "./clients";
import { staff } from "./staff";

export const calendarEventTypeEnum = pgEnum("calendar_event_type", [
  "master_calendar_hearing",
  "individual_hearing",
  "uscis_interview",
  "biometric",
  "filing_deadline",
  "service_request",
  "client_meeting",
  "internal_event",
]);

export const calendarEventStatusEnum = pgEnum("calendar_event_status", [
  "scheduled",
  "completed",
  "cancelled",
]);

export const judgeDeadlineTypeEnum = pgEnum("judge_deadline_type", [
  "30_days_before",
  "60_days_before",
  "custom",
]);

export const calendarEvents = pgTable("calendar_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: text("organization_id")
    .notNull()
    .references(() => organization.id),
  eventType: calendarEventTypeEnum("event_type").notNull(),
  status: calendarEventStatusEnum("status").notNull().default("scheduled"),
  title: text("title").notNull(),
  startTime: timestamp("start_time").notNull(),
  endTime: timestamp("end_time"),
  clientId: uuid("client_id").references(() => clients.id),
  caseId: uuid("case_id").references(() => cases.id, { onDelete: "cascade" }),
  assignedStaffId: uuid("assigned_staff_id").references(() => staff.id),
  teamId: text("team_id").references(() => team.id),
  location: text("location"),
  zoomLink: text("zoom_link"),
  notes: text("notes"),
  isAutoGenerated: boolean("is_auto_generated").notNull().default(false),
  parentEventId: uuid("parent_event_id").references(
    (): AnyPgColumn => calendarEvents.id,
  ),
  // MCH-specific
  filingSubmittedDate: date("filing_submitted_date"),
  detained: boolean("detained"),
  // IH-specific
  judgeDeadlineType: judgeDeadlineTypeEnum("judge_deadline_type"),
  customDeadlineDate: date("custom_deadline_date"),
  removabilityFindingDate: date("removability_finding_date"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export type CalendarEvent = typeof calendarEvents.$inferSelect;
export type NewCalendarEvent = typeof calendarEvents.$inferInsert;
