ALTER TABLE leads ADD COLUMN IF NOT EXISTS sms_consent boolean DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sms_consent_at timestamp;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sms_consent_source text;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS sms_opt_out_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS lead_id uuid REFERENCES leads(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'ad_hoc';
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS workflow_template_step_id uuid;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS pipeline_template_step_id uuid;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS phase text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS order_index integer;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_required boolean NOT NULL DEFAULT true;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS is_locked boolean NOT NULL DEFAULT false;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_by_id uuid;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS completed_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS override_rationale text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS override_by_id uuid;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS override_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reminder_3d_sent_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reminder_1d_sent_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS overdue_reminder_sent_at timestamp;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS time_taken_ms integer;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE tasks DROP COLUMN IF EXISTS progress;
