import { and, eq, gte, inArray, lte } from "drizzle-orm";
import { db } from "../../db/client";
import {
  CalendarEvent,
  calendarEvents,
  NewCalendarEvent,
} from "../../db/schema/calendar-events";
import { clients } from "../../db/schema/clients";
import { cases } from "../../db/schema/cases";
import { leads } from "../../db/schema/leads";
import { staff } from "../../db/schema/staff";
import { dayjs } from "../../utils/date";
import { getFirmTimezone } from "../settings/consultation/consultation-settings.service";

// ─── Helpers ─────────────────────────────────────────────────────────────────

const addDays = (d: Date, days: number): Date => {
  const result = new Date(d);
  result.setDate(result.getDate() + days);
  return result;
};

const daysBetween = (a: Date, b: Date): number =>
  Math.floor((b.getTime() - a.getTime()) / (1000 * 60 * 60 * 24));

// ─── Auto-deadline computation ────────────────────────────────────────────────

const buildMCHDeadlines = (event: CalendarEvent): NewCalendarEvent[] => {
  const deadlines: NewCalendarEvent[] = [];
  const hearingDate = new Date(event.startTime);

  if (event.filingSubmittedDate) {
    const filingDate = new Date(event.filingSubmittedDate);
    const diff = daysBetween(filingDate, hearingDate);

    if (diff >= 15) {
      deadlines.push({
        organizationId: event.organizationId,
        eventType: "filing_deadline",
        status: "scheduled",
        title: `Response Deadline — ${event.title}`,
        startTime: addDays(filingDate, 10),
        clientId: event.clientId,
        caseId: event.caseId,
        assignedStaffId: event.assignedStaffId,
        teamId: event.teamId,
        isAutoGenerated: true,
        parentEventId: event.id,
        notes:
          "Auto-generated: response deadline 10 days after filing date (MCH rule)",
      });
    }
    // < 15 days: note already stored on the hearing event — no separate deadline event
  }

  return deadlines;
};

const buildIHDeadlines = (event: CalendarEvent): NewCalendarEvent[] => {
  const deadlines: NewCalendarEvent[] = [];
  const hearingDate = new Date(event.startTime);

  // 30-day filing deadline for unrepresented, non-detained respondents
  if (!event.detained) {
    deadlines.push({
      organizationId: event.organizationId,
      eventType: "filing_deadline",
      status: "scheduled",
      title: `Filing Deadline — ${event.title}`,
      startTime: addDays(hearingDate, -30),
      clientId: event.clientId,
      caseId: event.caseId,
      assignedStaffId: event.assignedStaffId,
      teamId: event.teamId,
      isAutoGenerated: true,
      parentEventId: event.id,
      notes:
        "Auto-generated: filing deadline 30 days before Individual Hearing",
    });
  }

  // Judge-ordered document deadline
  if (event.judgeDeadlineType) {
    let deadlineDate: Date | null = null;

    if (event.judgeDeadlineType === "30_days_before") {
      deadlineDate = addDays(hearingDate, -30);
    } else if (event.judgeDeadlineType === "60_days_before") {
      deadlineDate = addDays(hearingDate, -60);
    } else if (
      event.judgeDeadlineType === "custom" &&
      event.customDeadlineDate
    ) {
      deadlineDate = new Date(event.customDeadlineDate);
    }

    if (deadlineDate) {
      deadlines.push({
        organizationId: event.organizationId,
        eventType: "filing_deadline",
        status: "scheduled",
        title: `Judge-Ordered Document Deadline — ${event.title}`,
        startTime: deadlineDate,
        clientId: event.clientId,
        caseId: event.caseId,
        assignedStaffId: event.assignedStaffId,
        teamId: event.teamId,
        isAutoGenerated: true,
        parentEventId: event.id,
        notes: "Auto-generated: judge-ordered document deadline (IH rule)",
      });
    }
  }

  // 60-day scheduling order from removability finding date
  if (event.removabilityFindingDate) {
    const findingDate = new Date(event.removabilityFindingDate);
    deadlines.push({
      organizationId: event.organizationId,
      eventType: "filing_deadline",
      status: "scheduled",
      title: `Scheduling Order Deadline — ${event.title}`,
      startTime: addDays(findingDate, 60),
      clientId: event.clientId,
      caseId: event.caseId,
      assignedStaffId: event.assignedStaffId,
      teamId: event.teamId,
      isAutoGenerated: true,
      parentEventId: event.id,
      notes:
        "Auto-generated: scheduling order deadline 60 days from removability finding",
    });
  }

  return deadlines;
};

const insertDeadlines = async (event: CalendarEvent): Promise<void> => {
  let deadlines: NewCalendarEvent[] = [];

  if (event.eventType === "master_calendar_hearing") {
    deadlines = buildMCHDeadlines(event);
  } else if (event.eventType === "individual_hearing") {
    deadlines = buildIHDeadlines(event);
  }

  if (deadlines.length) {
    await db.insert(calendarEvents).values(deadlines);
  }
};

const deleteAutoGeneratedChildren = async (parentId: string): Promise<void> => {
  await db
    .delete(calendarEvents)
    .where(
      and(
        eq(calendarEvents.parentEventId, parentId),
        eq(calendarEvents.isAutoGenerated, true),
      ),
    );
};

// ─── Shared: fetch a single event with joins ─────────────────────────────────

const fetchEventWithJoins = async (
  id: string,
  organizationId: string,
) => {
  const rows = await db
    .select({
      id: calendarEvents.id,
      eventType: calendarEvents.eventType,
      status: calendarEvents.status,
      title: calendarEvents.title,
      startTime: calendarEvents.startTime,
      endTime: calendarEvents.endTime,
      location: calendarEvents.location,
      zoomLink: calendarEvents.zoomLink,
      notes: calendarEvents.notes,
      isAutoGenerated: calendarEvents.isAutoGenerated,
      parentEventId: calendarEvents.parentEventId,
      teamId: calendarEvents.teamId,
      clientId: clients.id,
      clientDisplayName: clients.displayName,
      caseId: cases.id,
      caseNumber: cases.caseNumber,
      staffId: staff.id,
      staffFirstName: staff.firstName,
      staffLastName: staff.lastName,
      staffRole: staff.jobTitle,
      leadId: leads.id,
      leadFirstName: leads.firstName,
      leadLastName: leads.lastName,
    })
    .from(calendarEvents)
    .leftJoin(clients, eq(clients.id, calendarEvents.clientId))
    .leftJoin(cases, eq(cases.id, calendarEvents.caseId))
    .leftJoin(staff, eq(staff.id, calendarEvents.assignedStaffId))
    .leftJoin(leads, eq(leads.id, calendarEvents.leadId))
    .where(
      and(
        eq(calendarEvents.id, id),
        eq(calendarEvents.organizationId, organizationId),
      ),
    );

  const [row] = rows;
  if (!row) return null;

  return {
    id: row.id,
    eventType: row.eventType,
    status: row.status,
    title: row.title,
    startTime: row.startTime,
    endTime: row.endTime,
    location: row.location,
    zoomLink: row.zoomLink,
    notes: row.notes,
    isAutoGenerated: row.isAutoGenerated,
    parentEventId: row.parentEventId,
    teamId: row.teamId,
    client: row.clientId
      ? { id: row.clientId, name: row.clientDisplayName ?? "" }
      : null,
    case: row.caseId
      ? { id: row.caseId, caseNumber: row.caseNumber ?? "" }
      : null,
    assignedStaff: row.staffId
      ? {
          id: row.staffId,
          name: `${row.staffFirstName} ${row.staffLastName}`,
          role: row.staffRole,
        }
      : null,
    lead: row.leadId
      ? {
          id: row.leadId,
          name: `${row.leadFirstName} ${row.leadLastName}`,
        }
      : null,
  };
};

// ─── CRUD ─────────────────────────────────────────────────────────────────────

export const getCalendarEvents = async (
  organizationId: string,
  filters?: {
    year?: number;
    month?: number;
    teamId?: string;
    eventTypes?: string[];
  },
) => {
  const conditions = [eq(calendarEvents.organizationId, organizationId)];

  if (filters?.year && filters?.month) {
    const start = new Date(filters.year, filters.month - 1, 1);
    const end = new Date(filters.year, filters.month, 1);
    conditions.push(gte(calendarEvents.startTime, start));
    conditions.push(lte(calendarEvents.startTime, end));
  }

  if (filters?.teamId) {
    conditions.push(eq(calendarEvents.teamId, filters.teamId));
  }

  if (filters?.eventTypes?.length) {
    conditions.push(
      inArray(calendarEvents.eventType, filters.eventTypes as any[]),
    );
  }

  const rows = await db
    .select({
      id: calendarEvents.id,
      eventType: calendarEvents.eventType,
      status: calendarEvents.status,
      title: calendarEvents.title,
      startTime: calendarEvents.startTime,
      endTime: calendarEvents.endTime,
      location: calendarEvents.location,
      zoomLink: calendarEvents.zoomLink,
      notes: calendarEvents.notes,
      isAutoGenerated: calendarEvents.isAutoGenerated,
      parentEventId: calendarEvents.parentEventId,
      teamId: calendarEvents.teamId,
      clientId: clients.id,
      clientDisplayName: clients.displayName,
      caseId: cases.id,
      caseNumber: cases.caseNumber,
      staffId: staff.id,
      staffFirstName: staff.firstName,
      staffLastName: staff.lastName,
      staffRole: staff.jobTitle,
      leadId: leads.id,
      leadFirstName: leads.firstName,
      leadLastName: leads.lastName,
    })
    .from(calendarEvents)
    .leftJoin(clients, eq(clients.id, calendarEvents.clientId))
    .leftJoin(cases, eq(cases.id, calendarEvents.caseId))
    .leftJoin(staff, eq(staff.id, calendarEvents.assignedStaffId))
    .leftJoin(leads, eq(leads.id, calendarEvents.leadId))
    .where(and(...conditions));

  return rows.map((r) => ({
    id: r.id,
    eventType: r.eventType,
    status: r.status,
    title: r.title,
    startTime: r.startTime,
    endTime: r.endTime,
    location: r.location,
    zoomLink: r.zoomLink,
    notes: r.notes,
    isAutoGenerated: r.isAutoGenerated,
    parentEventId: r.parentEventId,
    teamId: r.teamId,
    client: r.clientId
      ? { id: r.clientId, name: r.clientDisplayName ?? "" }
      : null,
    case: r.caseId
      ? { id: r.caseId, caseNumber: r.caseNumber ?? "" }
      : null,
    assignedStaff: r.staffId
      ? {
          id: r.staffId,
          name: `${r.staffFirstName} ${r.staffLastName}`,
          role: r.staffRole,
        }
      : null,
    lead: r.leadId
      ? {
          id: r.leadId,
          name: `${r.leadFirstName} ${r.leadLastName}`,
        }
      : null,
  }));
};

export const getCalendarEventById = async (
  id: string,
  organizationId: string,
) => {
  const event = await fetchEventWithJoins(id, organizationId);
  if (!event) return null;

  const rawChildren = await db
    .select({
      id: calendarEvents.id,
      eventType: calendarEvents.eventType,
      status: calendarEvents.status,
      title: calendarEvents.title,
      startTime: calendarEvents.startTime,
      endTime: calendarEvents.endTime,
      location: calendarEvents.location,
      zoomLink: calendarEvents.zoomLink,
      notes: calendarEvents.notes,
      isAutoGenerated: calendarEvents.isAutoGenerated,
      parentEventId: calendarEvents.parentEventId,
      teamId: calendarEvents.teamId,
      clientId: clients.id,
      clientDisplayName: clients.displayName,
      caseId: cases.id,
      caseNumber: cases.caseNumber,
      staffId: staff.id,
      staffFirstName: staff.firstName,
      staffLastName: staff.lastName,
      staffRole: staff.jobTitle,
      leadId: leads.id,
      leadFirstName: leads.firstName,
      leadLastName: leads.lastName,
    })
    .from(calendarEvents)
    .leftJoin(clients, eq(clients.id, calendarEvents.clientId))
    .leftJoin(cases, eq(cases.id, calendarEvents.caseId))
    .leftJoin(staff, eq(staff.id, calendarEvents.assignedStaffId))
    .leftJoin(leads, eq(leads.id, calendarEvents.leadId))
    .where(
      and(
        eq(calendarEvents.parentEventId, id),
        eq(calendarEvents.isAutoGenerated, true),
        eq(calendarEvents.organizationId, organizationId),
      ),
    );

  const autoGeneratedDeadlines = rawChildren.map((r) => ({
    id: r.id,
    eventType: r.eventType,
    status: r.status,
    title: r.title,
    startTime: r.startTime,
    endTime: r.endTime,
    location: r.location,
    zoomLink: r.zoomLink,
    notes: r.notes,
    isAutoGenerated: r.isAutoGenerated,
    parentEventId: r.parentEventId,
    teamId: r.teamId,
    client: r.clientId
      ? { id: r.clientId, name: r.clientDisplayName ?? "" }
      : null,
    case: r.caseId
      ? { id: r.caseId, caseNumber: r.caseNumber ?? "" }
      : null,
    assignedStaff: r.staffId
      ? {
          id: r.staffId,
          name: `${r.staffFirstName} ${r.staffLastName}`,
          role: r.staffRole,
        }
      : null,
    lead: r.leadId
      ? {
          id: r.leadId,
          name: `${r.leadFirstName} ${r.leadLastName}`,
        }
      : null,
  }));

  return { ...event, autoGeneratedDeadlines };
};

export const createCalendarEvent = async (
  organizationId: string,
  data: Omit<
    NewCalendarEvent,
    | "id"
    | "organizationId"
    | "createdAt"
    | "updatedAt"
    | "isAutoGenerated"
    | "parentEventId"
  >,
) => {
  const [event] = await db
    .insert(calendarEvents)
    .values({ ...data, organizationId, isAutoGenerated: false })
    .returning();

  await insertDeadlines(event);

  return fetchEventWithJoins(event.id, organizationId);
};

export const updateCalendarEvent = async (
  id: string,
  organizationId: string,
  data: Partial<NewCalendarEvent>,
) => {
  const [existing] = await db
    .select({ status: calendarEvents.status })
    .from(calendarEvents)
    .where(
      and(
        eq(calendarEvents.id, id),
        eq(calendarEvents.organizationId, organizationId),
      ),
    )
    .limit(1);

  if (!existing) return null;
  if (existing.status === "completed" || existing.status === "cancelled") {
    throw new Error(
      `Cannot update a ${existing.status} event`,
    );
  }

  const [updated] = await db
    .update(calendarEvents)
    .set({ ...data, updatedAt: new Date() })
    .where(
      and(
        eq(calendarEvents.id, id),
        eq(calendarEvents.organizationId, organizationId),
      ),
    )
    .returning();

  if (!updated) return null;

  const isHearing =
    updated.eventType === "master_calendar_hearing" ||
    updated.eventType === "individual_hearing";

  if (isHearing && data.startTime) {
    await deleteAutoGeneratedChildren(id);
    await insertDeadlines(updated);
  }

  return fetchEventWithJoins(id, organizationId);
};

export const deleteCalendarEvent = async (
  id: string,
  organizationId: string,
): Promise<void> => {
  const [existing] = await db
    .select({ status: calendarEvents.status })
    .from(calendarEvents)
    .where(
      and(
        eq(calendarEvents.id, id),
        eq(calendarEvents.organizationId, organizationId),
      ),
    )
    .limit(1);

  if (!existing) return;
  if (existing.status === "completed" || existing.status === "cancelled") {
    throw new Error(
      `Cannot delete a ${existing.status} event`,
    );
  }

  await deleteAutoGeneratedChildren(id);
  await db
    .delete(calendarEvents)
    .where(
      and(
        eq(calendarEvents.id, id),
        eq(calendarEvents.organizationId, organizationId),
      ),
    );
};

// ─── Dashboard Strip ──────────────────────────────────────────────────────────

export const getCalendarStrip = async (
  organizationId: string,
  teamId?: string,
) => {
  // Bucket the 14-day strip against the firm's local calendar days.
  const tz = await getFirmTimezone(organizationId);
  const startDay = dayjs().tz(tz).startOf("day");
  const today = startDay.utc().toDate();
  const end = startDay.add(14, "day").utc().toDate();

  const conditions = [
    eq(calendarEvents.organizationId, organizationId),
    gte(calendarEvents.startTime, today),
    lte(calendarEvents.startTime, end),
  ];
  if (teamId) conditions.push(eq(calendarEvents.teamId, teamId));

  const events = await db
    .select({
      eventType: calendarEvents.eventType,
      startTime: calendarEvents.startTime,
    })
    .from(calendarEvents)
    .where(and(...conditions));

  const days: Record<
    string,
    {
      date: string;
      hearings: number;
      uscisInterviews: number;
      biometrics: number;
      other: number;
      total: number;
    }
  > = {};

  for (let i = 0; i < 14; i++) {
    const key = startDay.add(i, "day").format("YYYY-MM-DD");
    days[key] = {
      date: key,
      hearings: 0,
      uscisInterviews: 0,
      biometrics: 0,
      other: 0,
      total: 0,
    };
  }

  for (const e of events) {
    const key = dayjs.utc(e.startTime).tz(tz).format("YYYY-MM-DD");
    if (!days[key]) continue;
    days[key].total++;
    if (
      e.eventType === "master_calendar_hearing" ||
      e.eventType === "individual_hearing"
    ) {
      days[key].hearings++;
    } else if (e.eventType === "uscis_interview") {
      days[key].uscisInterviews++;
    } else if (e.eventType === "biometric") {
      days[key].biometrics++;
    } else {
      days[key].other++;
    }
  }

  return Object.values(days);
};

// ─── USCIS Service Request Events ────────────────────────────────────────────

export const createServiceRequestEvent = async (
  organizationId: string,
  clientId: string,
  caseId: string,
  clientName: string,
  formType: string,
  assignedStaffId?: string,
  teamId?: string,
) => {
  const [event] = await db
    .insert(calendarEvents)
    .values({
      organizationId,
      eventType: "service_request",
      status: "scheduled",
      title: `Service Request Due — ${clientName} — ${formType}`,
      startTime: new Date(),
      clientId,
      caseId,
      assignedStaffId,
      teamId,
      isAutoGenerated: true,
      notes: `USCIS processing time exceeded for ${formType}. Service request must be filed.`,
    })
    .returning();

  return event;
};

export const resolveServiceRequestEvents = async (
  caseId: string,
  organizationId: string,
): Promise<void> => {
  await db
    .delete(calendarEvents)
    .where(
      and(
        eq(calendarEvents.caseId, caseId),
        eq(calendarEvents.organizationId, organizationId),
        eq(calendarEvents.eventType, "service_request"),
        eq(calendarEvents.isAutoGenerated, true),
      ),
    );
};

export const scheduleNextServiceRequest = async (
  organizationId: string,
  clientId: string,
  caseId: string,
  clientName: string,
  formType: string,
  assignedStaffId?: string,
  teamId?: string,
) => {
  const nextDue = addDays(new Date(), 30);

  const [event] = await db
    .insert(calendarEvents)
    .values({
      organizationId,
      eventType: "service_request",
      status: "scheduled",
      title: `Service Request Due — ${clientName} — ${formType}`,
      startTime: nextDue,
      clientId,
      caseId,
      assignedStaffId,
      teamId,
      isAutoGenerated: true,
      notes: `Follow-up service request due 30 days after last submission for ${formType}.`,
    })
    .returning();

  return event;
};

export class CalendarService {
  getCalendarEvents = getCalendarEvents;
  getCalendarEventById = getCalendarEventById;
  createCalendarEvent = createCalendarEvent;
  updateCalendarEvent = updateCalendarEvent;
  deleteCalendarEvent = deleteCalendarEvent;
  getCalendarStrip = getCalendarStrip;
  createServiceRequestEvent = createServiceRequestEvent;
  resolveServiceRequestEvents = resolveServiceRequestEvents;
  scheduleNextServiceRequest = scheduleNextServiceRequest;
}
