import { z } from "zod";
import {
  calendarEventStatusEnum,
  calendarEventTypeEnum,
  judgeDeadlineTypeEnum,
} from "../../db/schema/calendar-events";

/**
 * Request schemas for the calendar module.
 *
 * Replaces `CommonValidation.optionalBody()` on create and update. Both fed
 * `Partial<NewCalendarEvent>` straight into `.set()`, so `organizationId`,
 * `isAutoGenerated` and `parentEventId` were all writable by the caller —
 * the last two are how the system distinguishes generated deadline chains from
 * events a person entered.
 */

const uuid = z.string().uuid();
const isoDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "Expected a date in YYYY-MM-DD format");

export const calendarEventIdParams = z.object({ id: uuid });

/**
 * `organizationId`, `isAutoGenerated` and `parentEventId` are absent by design:
 * tenancy and generated-event provenance are the service's to set.
 */
const eventFields = {
  eventType: z.enum(calendarEventTypeEnum.enumValues),
  status: z.enum(calendarEventStatusEnum.enumValues).optional(),
  title: z.string().trim().min(1).max(300),
  startTime: z.coerce.date(),
  endTime: z.coerce.date().nullable().optional(),
  clientId: uuid.nullable().optional(),
  caseId: uuid.nullable().optional(),
  leadId: uuid.nullable().optional(),
  assignedStaffId: uuid.nullable().optional(),
  teamId: z.string().min(1).nullable().optional(),
  location: z.string().trim().max(500).nullable().optional(),
  zoomLink: z.string().trim().url().max(1000).nullable().optional(),
  notes: z.string().trim().max(10_000).nullable().optional(),
  filingSubmittedDate: isoDate.nullable().optional(),
  detained: z.boolean().nullable().optional(),
  judgeDeadlineType: z.enum(judgeDeadlineTypeEnum.enumValues).nullable().optional(),
  customDeadlineDate: isoDate.nullable().optional(),
  removabilityFindingDate: isoDate.nullable().optional(),
} as const;

/** An event that ends before it starts is a data error, not a preference. */
const endAfterStart = <T extends { startTime?: Date; endTime?: Date | null }>(
  body: T,
) => !body.startTime || !body.endTime || body.endTime > body.startTime;

export const createCalendarEventBody = z
  .object(eventFields)
  .strict()
  .refine(endAfterStart, {
    message: "endTime must be after startTime",
    path: ["endTime"],
  });

export const updateCalendarEventBody = z
  .object(eventFields)
  .partial()
  .strict()
  .refine((body) => Object.keys(body).length > 0, {
    message: "Provide at least one field to update",
  })
  .refine(endAfterStart, {
    message: "endTime must be after startTime",
    path: ["endTime"],
  });

export type CreateCalendarEventInput = z.infer<typeof createCalendarEventBody>;
export type UpdateCalendarEventInput = z.infer<typeof updateCalendarEventBody>;
