/**
 * Performs the side effect behind a contextual action.
 *
 * The vocabulary and which actions each issue offers live in `actions.ts`; this
 * file is only the "what happens when you click it" half. Each handler reuses an
 * existing primitive (email, a lead task, a calendar event) rather than a
 * case-review-specific one.
 *
 * Effects that outgrow this — a real reminder cadence, attorney routing for
 * cases once a case task table exists — should replace a handler here, not add
 * branching to the caller.
 */
import { and, count, eq } from "drizzle-orm";
import { db } from "../../db/client";
import { calendarEvents } from "../../db/schema/calendar-events";
import { caseIssues } from "../../db/schema/case-issues";
import { clients } from "../../db/schema/clients";
import { leadTasks } from "../../db/schema/lead-tasks";
import { leads } from "../../db/schema/leads";
import { BadRequestError } from "../../utils/error/app-error";
import { emailService } from "../../utils/email/email.service";
import type { ActionDef } from "./actions";

type IssueRow = typeof caseIssues.$inferSelect;

/**
 * Collaborators the dispatch depends on, injected so a check can drive the real
 * handlers with a fake mailer instead of sending mail.
 */
export type ActionDeps = {
  sendEmail: (opts: { to: string; subject: string; html: string }) => Promise<void>;
};

export const defaultActionDeps: ActionDeps = {
  sendEmail: (opts) => emailService.sendEmail(opts),
};

/** Where a navigate action should take the user; no effect is performed. */
export type NavigateResult = {
  kind: "navigate";
  target: "case" | "document";
  scenario: { type: "lead" | "case"; id: string };
};

export type MutationResult = { kind: "mutation" };

export type DispatchResult = NavigateResult | MutationResult;

/** Resolve the client/lead email an outbound action should reach. */
const resolveRecipientEmail = async (issue: IssueRow): Promise<string> => {
  if (issue.leadId) {
    const [row] = await db
      .select({ email: leads.email })
      .from(leads)
      .where(eq(leads.id, issue.leadId))
      .limit(1);
    if (row?.email) return row.email;
  } else if (issue.clientId) {
    const [row] = await db
      .select({ email: clients.email })
      .from(clients)
      .where(eq(clients.id, issue.clientId))
      .limit(1);
    if (row?.email) return row.email;
  }
  throw new BadRequestError("This matter has no contact email to reach");
};

const notify = async (
  deps: ActionDeps,
  issue: IssueRow,
  subject: string,
  body: string,
) => {
  const to = await resolveRecipientEmail(issue);
  await deps.sendEmail({
    to,
    subject,
    html: `<p>${body}</p>`,
  });
};

/** Create a lead task carrying the issue, for the attorney-routing actions. */
const createLeadTask = async (
  issue: IssueRow,
  staffId: string | undefined,
  title: string,
) => {
  if (!issue.leadId) {
    // Should be unreachable: the registry only offers these on lead issues.
    throw new BadRequestError("Task actions apply to lead-stage matters only");
  }
  // Append after the lead's existing tasks.
  const [{ n }] = await db
    .select({ n: count() })
    .from(leadTasks)
    .where(eq(leadTasks.leadId, issue.leadId));

  await db.insert(leadTasks).values({
    organizationId: issue.organizationId,
    leadId: issue.leadId,
    title,
    description: "Raised by AI case review.",
    orderIndex: Number(n),
    pipelineStage: "conflict_check",
    assignedToId: staffId ?? null,
  });
};

/** Create a case-scoped calendar reminder for the set-calendar-alert action. */
const createCalendarAlert = async (issue: IssueRow, title: string) => {
  if (!issue.caseId) {
    throw new BadRequestError("Calendar alerts apply to open cases only");
  }
  await db.insert(calendarEvents).values({
    organizationId: issue.organizationId,
    eventType: "filing_deadline",
    title,
    // A placeholder time the reviewer edits in the calendar; the point is the
    // reminder exists and is linked to the matter.
    startTime: new Date(Date.now() + 24 * 60 * 60 * 1000),
    caseId: issue.caseId,
    clientId: issue.clientId ?? null,
    isAutoGenerated: true,
    notes: "Created from AI case review",
  });
};

/**
 * Run the effect for `action` against `issue`. Navigate actions return where to
 * go and touch nothing. The caller records the event and moves the issue to
 * under_review.
 */
export const dispatchAction = async (
  deps: ActionDeps,
  issue: IssueRow,
  action: ActionDef,
  staffId: string | undefined,
): Promise<DispatchResult> => {
  if (action.kind === "navigate") {
    return {
      kind: "navigate",
      target: action.target ?? "case",
      scenario: issue.leadId
        ? { type: "lead", id: issue.leadId }
        : { type: "case", id: issue.caseId! },
    };
  }

  switch (action.key) {
    case "request_reupload":
      await notify(
        deps,
        issue,
        "A document needs to be re-uploaded",
        "Please re-upload the document your legal team flagged for review.",
      );
      break;
    case "send_client_reminder":
      await notify(
        deps,
        issue,
        "Reminder from your legal team",
        "Your legal team is waiting on an outstanding item for your matter.",
      );
      break;
    case "send_urgent_reminder":
      await notify(
        deps,
        issue,
        "Urgent: action needed on your matter",
        "An item on your matter is time-sensitive. Please act as soon as possible.",
      );
      break;
    case "assign_to_attorney":
    case "escalate_to_attorney":
    case "flag_for_attorney":
      await createLeadTask(issue, staffId, `Attorney review: ${action.label}`);
      break;
    case "request_postponement":
      await createLeadTask(issue, staffId, "Request deadline postponement");
      break;
    case "set_calendar_alert":
      await createCalendarAlert(issue, "AI review: deadline alert");
      break;
    default:
      throw new BadRequestError(`Action ${action.key} has no handler`);
  }

  return { kind: "mutation" };
};

/** Guard: the issue exists and belongs to the org. */
export const loadIssueForAction = async (
  organizationId: string,
  id: string,
): Promise<IssueRow | undefined> => {
  const [row] = await db
    .select()
    .from(caseIssues)
    .where(and(eq(caseIssues.id, id), eq(caseIssues.organizationId, organizationId)))
    .limit(1);
  return row;
};
